###

POST  http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "jonas10@jonas.lt",
  "password": "jonas123"
}

###

POST  http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "jonas10@jonas.lt",
  "password": "jonas123"
}

###