###

POST  http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "jonas1@jonas.lt",
  "password": "jonas123"
}

###

POST  http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "jonas1@jonas.lt",
  "password": "jonas123"
}

###

GET http://localhost:8080/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY1Njc5MzczNX0.4i33hH9nw8OVXwWiLzyzDGu7FUsIDGuK8fX4x8h5NwI
###

GET http://localhost:8080/groups/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY1Njc5MzczNX0.4i33hH9nw8OVXwWiLzyzDGu7FUsIDGuK8fX4x8h5NwI
###

###

PUT http://localhost:8080/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY1Njc5MzczNX0.4i33hH9nw8OVXwWiLzyzDGu7FUsIDGuK8fX4x8h5NwI

{
  "id": 6,
  "type": "OUTCOME",
  "title": "Restaurants"
}

###

###

POST http://localhost:8080/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY1Njc5MzczNX0.4i33hH9nw8OVXwWiLzyzDGu7FUsIDGuK8fX4x8h5NwI

{
  "type": "OUTCOME",
  "title": "Alcohol Drinks 1"
}

###

###

DELETE http://localhost:8080/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY1Njc5MzczNX0.4i33hH9nw8OVXwWiLzyzDGu7FUsIDGuK8fX4x8h5NwI

{
  "groupId":1
}

###


GET http://localhost:8080/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY1Njc5MzczNX0.4i33hH9nw8OVXwWiLzyzDGu7FUsIDGuK8fX4x8h5NwI
###

GET http://localhost:8080/transactions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY1Njc5MzczNX0.4i33hH9nw8OVXwWiLzyzDGu7FUsIDGuK8fX4x8h5NwI


###

PUT http://localhost:8080/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY1Njc5MzczNX0.4i33hH9nw8OVXwWiLzyzDGu7FUsIDGuK8fX4x8h5NwI

{
  "id": 6,
  "groupId": 8,
  "transactionDate": "2022-06-21",
  "amount": 20,
  "comment": ""
}

###


POST http://localhost:8080/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY1Njc5MzczNX0.4i33hH9nw8OVXwWiLzyzDGu7FUsIDGuK8fX4x8h5NwI

{
  "groupId": 10,
  "transactionDate": "2022-06-21",
  "amount": 300,
  "comment": "telia"
}

###


DELETE http://localhost:8080/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY1Njc5MzczNX0.4i33hH9nw8OVXwWiLzyzDGu7FUsIDGuK8fX4x8h5NwI

{
  "transactionId":1
}

###

GET http://localhost:8080/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY1Njc5MzczNX0.4i33hH9nw8OVXwWiLzyzDGu7FUsIDGuK8fX4x8h5NwI


###